Feature/fixtures
kiasha10/BlitzBoard pull request #12
Opened 2024-05-21 13:44 UTC by kiasha10

[Feature/Merge] - Feature/fixtures

[Merge]  feature/fixtures → dev
[Feature] - Fixtures

 ## Description
Added Fixtures feature

<img width="512" alt="Screenshot 2024-05-21 at 15 43 47" src="https://github.com/kiasha10/BlitzBoard/assets/148989511/0e97d397-bf41-4765-ab7c-a1fbdd417348">

## Checklist
Please review and check the following before submitting this pull request:
- [ ] The code follows the project's coding standards.
- [ ] 100% Unit test coverage for View Models

2024-05-22 05:39 UTC, kiasha10 commented on BlitzBoard/Features/FixturesScreenTableViewCell.swift
> +
make this outlet private

2024-05-22 05:42 UTC, kiasha10 commented on BlitzBoard/Features/FixturesScreenViewModel.swift
> +
add marks for these variables.

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/DateFormatter.swift
> +
Add MARK: Extensions and clear extra comment spacing above filename.swift

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/Features/FixturesModel.swift
> +// MARK: - Fixtures Model
fix indentation for MARK

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/Features/FixturesScreenViewController.swift
> +    // MARK: Properties
Change "properties" to "Variables"

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/Features/FixturesScreenViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
private

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/Features/FixturesScreenViewController.swift
> +// MARK: - Extensions
indent

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/Features/FixturesScreenViewController.swift
> +
remove extra line

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/Features/FixturesScreenViewModel.swift
> +import Foundation
space above import statement

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/ServiceLayer/Constants.swift
> +    static let matchDateMonths = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
line space

2024-05-22 07:17 UTC, kiasha10 commented on BlitzBoard/Features/FixturesScreenTableViewCell.swift
> +import UIKit
space above import

2024-05-22 07:56 UTC, sjacobs1 commented on BlitzBoard/Features/FixturesScreenViewController.swift
> +    private lazy var viewModel = FixturesScreenViewModel(repository: FixturesScreenRepository(), delegate: self )
remove spacing between variables

2024-05-22 07:56 UTC, sjacobs1 commented on BlitzBoard/Features/FixturesScreenRepository.swift
> +
add mark for variable

2024-05-22 07:57 UTC, sjacobs1 commented on BlitzBoard/Features/FixturesScreenViewModel.swift
> +    private weak var delegate: ViewModelDelegate?
remove space between variables

2024-05-23 06:26 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenRepository.swift
> +typealias FixturesResult = (Result<[FixturesModel], APIError>)
```suggestion
typealias FixturesResult = (Result<[FixturesModel], APIError>) -> Void
```

2024-05-23 06:26 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenRepository.swift
> +    func fetchFixtures(completion: @escaping(FixturesResult) -> Void)
```suggestion
    func fetchFixtures(completion: @escaping FixturesResult)
```

2024-05-23 06:26 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenRepository.swift
> +    func fetchFixtures(completion: @escaping (FixturesResult) -> Void) {
Just update this too

2024-05-23 06:35 UTC, simekanidvt requested changes
Jus a few thing you need to clean up. Otherwise It's looking good. And good job on the errors you picked up when reviewing

2024-05-23 06:35 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenViewController.swift
> +    var fixtures: [FixturesModel] = []
Why do you have this property in your view controller? 
It should be in your viewModel since it is not UI related

2024-05-23 06:35 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenViewModel.swift
> +
Unnecessary empty line

2024-05-23 06:35 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenViewModel.swift
> +    var fetchNumberOfGames: Int {
```suggestion
    var numberOfGames: Int {
```
No need to use the word fetch for just extracting variables

2024-05-23 06:35 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenViewModel.swift
> +    func fetchFixtures(at index: Int) -> FixturesModel {
Same here

2024-05-23 06:35 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenViewModel.swift
> +        repository.fetchFixtures {[weak self] result in
```suggestion
        repository.fetchFixtures { [weak self] result in
```

2024-05-23 06:35 UTC, simekanidvt commented on BlitzBoard/Features/FixturesScreenViewModel.swift
> +                print("Error: \(error)")
Are you going to remove this print?

2024-05-23 06:35 UTC, simekanidvt commented on BlitzBoard/Features/HomeScreenViewController.swift
> +        else {
You can move else to the previous line

2024-05-23 06:35 UTC, simekanidvt commented on BlitzBoard/Features/HomeScreenViewModel.swift
>      var fetchNumberOfTeams: Int {
revise naming

2024-05-23 12:20 UTC, kieran-woodrow approved these changes
Good job Kiasha, keep it up👏🏼

2024-05-23 13:09 UTC, simekanidvt approved these changes

2024-05-23 16:36 UTC, merged