Added Loading Indicators to table views
kiasha10/BlitzBoard pull request #15
Opened 2024-05-24 09:24 UTC by kiasha10

[Feature/Merge] - Added loading spinners to table views

[Merge] feature/loading-indicators → dev
[Feature] - loading-indicators

 ## Description
Added Loading Indicators

![Simulator Screenshot - iPhone 15 Pro - 2024-05-24 at 11 23 33](https://github.com/kiasha10/BlitzBoard/assets/148989511/f52867d7-9887-4b98-be6c-49a73ec3f8e8)
![Simulator Screenshot - iPhone 15 Pro - 2024-05-24 at 11 24 02](https://github.com/kiasha10/BlitzBoard/assets/148989511/ac837265-3017-4644-ab47-3522e6536b0f)

## Checklist
Please review and check the following before submitting this pull request:
- [ ] The code follows the project's coding standards.
- [ ] 100% Unit test coverage for View Models

2024-05-24 10:59 UTC, kieran-woodrow requested changes

2024-05-24 10:59 UTC, kieran-woodrow commented on BlitzBoard/Features/FixturesScreenViewController.swift
> +            sleep(3)
so usually you don't want to have this on a timer, you want to link this to when your service call is actually complete. So the spinner.stopAnimating() will be called in the .finished of the viewModel when it fetches the data from the service

2024-05-24 10:59 UTC, kieran-woodrow commented on BlitzBoard/Features/HomeScreenViewController.swift
> +    @IBOutlet weak var spinner: UIActivityIndicatorView!
private please :)

2024-05-24 11:17 UTC, kieran-woodrow requested changes

2024-05-24 11:17 UTC, kieran-woodrow commented on BlitzBoard/Features/HomeScreenViewController.swift
> +            sleep(2)
same as above comment

2024-05-26 12:34 UTC, simekanidvt approved these changes

2024-05-26 12:45 UTC, ksookdhew approved these changes

2024-05-27 07:03 UTC, kieran-woodrow approved these changes

2024-05-27 07:04 UTC, merged